// <auto-generated />
using System;
using EventManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventManager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250817231038_AddFeedback")]
    partial class AddFeedback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("EventManager.Data.Entities.Events.DiscordEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId");

                    b.HasIndex("IsCompleted");

                    b.ToTable("DiscordEvent", (string)null);
                });

            modelBuilder.Entity("EventManager.Data.Entities.Events.EventFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Critic")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiscordEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Good")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Repeat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suggestion")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordEventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventFeedback", (string)null);
                });

            modelBuilder.Entity("EventManager.Data.Entities.Events.EventRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiscordEventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordEventId", "Type")
                        .IsUnique();

                    b.ToTable("EventRestriction", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EventManager.Data.Entities.Events.QOTD.QotdMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("QuestionId");

                    b.ToTable("QotdMessage", (string)null);
                });

            modelBuilder.Entity("EventManager.Data.Entities.Events.QOTD.QotdQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QotdQuestion", (string)null);
                });

            modelBuilder.Entity("EventManager.Data.Entities.Notifications.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowReminderForEvent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowReminderInPrivateMessage")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("UserPreference", (string)null);
                });

            modelBuilder.Entity("EventManager.Data.Entities.Restrictions.FskRestrictions", b =>
                {
                    b.HasBaseType("EventManager.Data.Entities.Events.EventRestriction");

                    b.Property<int?>("MaxAlter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinAlter")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("EventManager.Data.Entities.Events.EventFeedback", b =>
                {
                    b.HasOne("EventManager.Data.Entities.Events.DiscordEvent", "DiscordEvent")
                        .WithMany()
                        .HasForeignKey("DiscordEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscordEvent");
                });

            modelBuilder.Entity("EventManager.Data.Entities.Events.EventRestriction", b =>
                {
                    b.HasOne("EventManager.Data.Entities.Events.DiscordEvent", "DiscordEvent")
                        .WithMany("Restrictions")
                        .HasForeignKey("DiscordEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscordEvent");
                });

            modelBuilder.Entity("EventManager.Data.Entities.Events.QOTD.QotdMessage", b =>
                {
                    b.HasOne("EventManager.Data.Entities.Events.QOTD.QotdQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EventManager.Data.Entities.Events.DiscordEvent", b =>
                {
                    b.Navigation("Restrictions");
                });
#pragma warning restore 612, 618
        }
    }
}
